/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Calendar } from "./Calendar";
export type { CalendarFactory } from "./CalendarFactory";
export type { CalendarStorage } from "./CalendarStorage";
export type { CustomOwnable } from "./CustomOwnable";
