/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Calendar",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Calendar__factory>;
    getContractFactory(
      name: "CustomOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CustomOwnable__factory>;
    getContractFactory(
      name: "CalendarFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CalendarFactory__factory>;
    getContractFactory(
      name: "CalendarStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CalendarStorage__factory>;

    getContractAt(
      name: "Calendar",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Calendar>;
    getContractAt(
      name: "CustomOwnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CustomOwnable>;
    getContractAt(
      name: "CalendarFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CalendarFactory>;
    getContractAt(
      name: "CalendarStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CalendarStorage>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
