/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as calendarSol from "./Calendar.sol";
export type { calendarSol };
export type { CalendarFactory } from "./CalendarFactory";
export type { CalendarStorage } from "./CalendarStorage";
export * as factories from "./factories";
export type { Calendar } from "./Calendar.sol/Calendar";
export { Calendar__factory } from "./factories/Calendar.sol/Calendar__factory";
export type { CustomOwnable } from "./Calendar.sol/CustomOwnable";
export { CustomOwnable__factory } from "./factories/Calendar.sol/CustomOwnable__factory";
export { CalendarFactory__factory } from "./factories/CalendarFactory__factory";
export { CalendarStorage__factory } from "./factories/CalendarStorage__factory";
