/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace CalendarStorage {
  export type MeetingStruct = {
    attendee: string;
    hour: BigNumberish;
    minute: BigNumberish;
    duration: BigNumberish;
  };

  export type MeetingStructOutput = [string, number, number, number] & {
    attendee: string;
    hour: number;
    minute: number;
    duration: number;
  };
}

export interface CalendarInterface extends utils.Interface {
  functions: {
    "availableDays(uint256)": FunctionFragment;
    "bookMeeting(uint256,uint256,uint256,uint16,uint16,uint16)": FunctionFragment;
    "cancelMeeting(uint256,uint256,uint256,uint256)": FunctionFragment;
    "changeAvailableTimes(uint16,uint16,uint16)": FunctionFragment;
    "dateToMeetings(uint256,uint256,uint256,uint256)": FunctionFragment;
    "emailAddress()": FunctionFragment;
    "getMeetings(uint256,uint256,uint256)": FunctionFragment;
    "initialize(address,string,bool[7],uint16,uint16,uint16)": FunctionFragment;
    "owner()": FunctionFragment;
    "setAvailableDays(bool[7])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "availableDays"
      | "bookMeeting"
      | "cancelMeeting"
      | "changeAvailableTimes"
      | "dateToMeetings"
      | "emailAddress"
      | "getMeetings"
      | "initialize"
      | "owner"
      | "setAvailableDays"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "availableDays",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bookMeeting",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMeeting",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAvailableTimes",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dateToMeetings",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emailAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMeetings",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      string,
      boolean[],
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAvailableDays",
    values: [boolean[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "availableDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bookMeeting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMeeting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeAvailableTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dateToMeetings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emailAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMeetings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAvailableDays",
    data: BytesLike
  ): Result;

  events: {
    "MeetingBooked(address,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "MeetingCancelled(address,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MeetingBooked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MeetingCancelled"): EventFragment;
}

export interface MeetingBookedEventObject {
  attendee: string;
  year: BigNumber;
  month: BigNumber;
  day: BigNumber;
  hour: BigNumber;
  minute: BigNumber;
  duration: BigNumber;
}
export type MeetingBookedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  MeetingBookedEventObject
>;

export type MeetingBookedEventFilter = TypedEventFilter<MeetingBookedEvent>;

export interface MeetingCancelledEventObject {
  attendee: string;
  year: BigNumber;
  month: BigNumber;
  day: BigNumber;
  hour: BigNumber;
  minute: BigNumber;
  duration: BigNumber;
}
export type MeetingCancelledEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  MeetingCancelledEventObject
>;

export type MeetingCancelledEventFilter =
  TypedEventFilter<MeetingCancelledEvent>;

export interface Calendar extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CalendarInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    availableDays(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    bookMeeting(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      _hour: BigNumberish,
      _minute: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelMeeting(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      _arrayPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeAvailableTimes(
      _availableStartHour: BigNumberish,
      _availableStartMinute: BigNumberish,
      _durationInMinutes: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    dateToMeetings(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, number] & {
        attendee: string;
        hour: number;
        minute: number;
        duration: number;
      }
    >;

    emailAddress(overrides?: CallOverrides): Promise<[string]>;

    getMeetings(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[CalendarStorage.MeetingStructOutput[]]>;

    initialize(
      _owner: string,
      _emailAddress: string,
      _availableDays: boolean[],
      _earliestHour: BigNumberish,
      _earliestMinute: BigNumberish,
      _minutesAvailable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    setAvailableDays(
      _availableDays: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  availableDays(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  bookMeeting(
    _year: BigNumberish,
    _month: BigNumberish,
    _day: BigNumberish,
    _hour: BigNumberish,
    _minute: BigNumberish,
    _duration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelMeeting(
    _year: BigNumberish,
    _month: BigNumberish,
    _day: BigNumberish,
    _arrayPosition: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeAvailableTimes(
    _availableStartHour: BigNumberish,
    _availableStartMinute: BigNumberish,
    _durationInMinutes: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  dateToMeetings(
    arg0: BigNumberish,
    arg1: BigNumberish,
    arg2: BigNumberish,
    arg3: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, number, number, number] & {
      attendee: string;
      hour: number;
      minute: number;
      duration: number;
    }
  >;

  emailAddress(overrides?: CallOverrides): Promise<string>;

  getMeetings(
    _year: BigNumberish,
    _month: BigNumberish,
    _day: BigNumberish,
    overrides?: CallOverrides
  ): Promise<CalendarStorage.MeetingStructOutput[]>;

  initialize(
    _owner: string,
    _emailAddress: string,
    _availableDays: boolean[],
    _earliestHour: BigNumberish,
    _earliestMinute: BigNumberish,
    _minutesAvailable: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  setAvailableDays(
    _availableDays: boolean[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    availableDays(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    bookMeeting(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      _hour: BigNumberish,
      _minute: BigNumberish,
      _duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelMeeting(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      _arrayPosition: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeAvailableTimes(
      _availableStartHour: BigNumberish,
      _availableStartMinute: BigNumberish,
      _durationInMinutes: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    dateToMeetings(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, number] & {
        attendee: string;
        hour: number;
        minute: number;
        duration: number;
      }
    >;

    emailAddress(overrides?: CallOverrides): Promise<string>;

    getMeetings(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      overrides?: CallOverrides
    ): Promise<CalendarStorage.MeetingStructOutput[]>;

    initialize(
      _owner: string,
      _emailAddress: string,
      _availableDays: boolean[],
      _earliestHour: BigNumberish,
      _earliestMinute: BigNumberish,
      _minutesAvailable: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    setAvailableDays(
      _availableDays: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "MeetingBooked(address,uint256,uint256,uint256,uint256,uint256,uint256)"(
      attendee?: string | null,
      year?: null,
      month?: null,
      day?: null,
      hour?: null,
      minute?: null,
      duration?: null
    ): MeetingBookedEventFilter;
    MeetingBooked(
      attendee?: string | null,
      year?: null,
      month?: null,
      day?: null,
      hour?: null,
      minute?: null,
      duration?: null
    ): MeetingBookedEventFilter;

    "MeetingCancelled(address,uint256,uint256,uint256,uint256,uint256,uint256)"(
      attendee?: string | null,
      year?: null,
      month?: null,
      day?: null,
      hour?: null,
      minute?: null,
      duration?: null
    ): MeetingCancelledEventFilter;
    MeetingCancelled(
      attendee?: string | null,
      year?: null,
      month?: null,
      day?: null,
      hour?: null,
      minute?: null,
      duration?: null
    ): MeetingCancelledEventFilter;
  };

  estimateGas: {
    availableDays(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bookMeeting(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      _hour: BigNumberish,
      _minute: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelMeeting(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      _arrayPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeAvailableTimes(
      _availableStartHour: BigNumberish,
      _availableStartMinute: BigNumberish,
      _durationInMinutes: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    dateToMeetings(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    emailAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getMeetings(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _owner: string,
      _emailAddress: string,
      _availableDays: boolean[],
      _earliestHour: BigNumberish,
      _earliestMinute: BigNumberish,
      _minutesAvailable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    setAvailableDays(
      _availableDays: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    availableDays(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bookMeeting(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      _hour: BigNumberish,
      _minute: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelMeeting(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      _arrayPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeAvailableTimes(
      _availableStartHour: BigNumberish,
      _availableStartMinute: BigNumberish,
      _durationInMinutes: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    dateToMeetings(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    emailAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMeetings(
      _year: BigNumberish,
      _month: BigNumberish,
      _day: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _owner: string,
      _emailAddress: string,
      _availableDays: boolean[],
      _earliestHour: BigNumberish,
      _earliestMinute: BigNumberish,
      _minutesAvailable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAvailableDays(
      _availableDays: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
