name: Publish Docker Image

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./back-end

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build . -t bishbashbosh/alliance:${{ steps.get_version.outputs.version }} -t bishbashbosh/alliance:latest
      - name: Push the Docker image
        run: docker push -a bishbashbosh/alliance
