name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bishbashbosh/alliance:${{ steps.get_version.outputs.version }}
      - name: Push the tagged Docker image
        run: docker push bishbashbosh/alliance:${{ steps.get_version.outputs.version }}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag bishbashbosh/alliance:latest
      - name: Push the latest Docker image
        run: docker push bishbashbosh/alliance:latest
