name: alliance front-end CI

on: [push]

defaults:
  run:
    working-directory: ./front-end

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: mv ./.env.github .env
    - run: npm ci
    - run: npm run coverage
