name: alliance front-end CI

on: 
  push:
    paths-ignore:
      - 'back-end'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front-end

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front-end/package-lock.json
    - run: mv ./.env.github .env
    - run: npm ci
    - run: npm run coverage
