# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: alliance CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies 
      run: npm ci
    - name: Copy config 
      run: mv ./.env.github .env
    - name: Compile 
      run: npx hardhat compile
    - name: Run tests & gas usage
      run: npx hardhat test
    - name: Run test coverage
      run: npx hardhat coverage
    - name: Create bash profile
      run: touch ~/.bash_profile
    - name: Run static analysis
      uses: crytic/slither-action@v0.1.1
      continue-on-error: true
      id: slither
      with:
        node-version: ${{ matrix.node-version }}
        sarif: results.sarif
    - name: Upload static analysis results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
