name: alliance static analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v3
    - name: Copy config 
      run: mv ./.env.github .env
    - name: Run static analysis
      uses: crytic/slither-action@v0.1.1
      continue-on-error: true
      id: slither
      with:
        node-version: 16
        sarif: results.sarif
    - name: Upload static analysis results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
