name: alliance static analysis

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Create bash profile
      run: touch ~/.bash_profile
    - name: Verify bash profile
      run: ls -lart ~
    - name: Run static analysis
      uses: crytic/slither-action@v0.1.1
      continue-on-error: true
      id: slither
      with:
        node-version: ${{ matrix.node-version }}
        sarif: results.sarif
    - name: Upload static analysis results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
